name: ekyc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0
  camera: ^0.11.1
  path: ^1.9.0
  image: ^4.0.17
  flutter_tesseract_ocr: ^0.4.28
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  http: ^1.3.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  dio: ^5.8.0+1
  open_file: ^3.5.10
  intl: ^0.20.2
  image_cropper: ^9.0.0
  google_mlkit_face_detection: ^0.12.0
  google_ml_kit: ^0.19.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/tessdata/
  - assets/tessdata/ara.traineddata
  - assets/tessdata_config.json

